### ISSUE TITLE
PaymentInstance and autoclose Issue

### ISSUE THREAD

**Issue by olajiredominic** [ashinzekene/angular-rave#24] opened 2019-10-28 01:24 UTC
I tried Importing "PaymentInstance" it is not a member of what the module exports.

apparently property "autoClose" doesn't event exist on both the component or the directive class.

Can't bind to 'autoClose' since it isn't a known property of 'button'. ("
        #raveBtn
        angular-rave
        [ERROR ->][autoClose]="true"
        [raveOptions]="paymentOptions",
        (callback)="saveResponse($event)"
"): ng:///OrderDetailsPageModule/OrderDetailsPage.html@82:8

used as <button
        #raveBtn
        angular-rave
        [autoClose]="true"
        [raveOptions]="paymentOptions",
        (callback)="saveResponse($event)"
        (onclose)="paymentCancelled()"
        class="raveBtn" 
      >PAY NOW</button>

**Comment by ashinzekene** [comment] 2019-10-28 01:36
What version of `angular-rave` do you have installed?

**Comment by olajiredominic** [comment] 2019-10-28 19:31
I had version 1.2.1 installed. Now upgraded to the latest 2.x.x. But still the frame doesn't close after transaction completion

**Comment by ashinzekene** [comment] 2019-10-28 19:59
I guess, your other issues have been resolved.  If you used either the `[autoClose]` input or you closed it manually like so, 

```ts
import { Component } from '@angular/core';
import { PaymentInstance } from 'angular-rave';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  paymentInstance: PaymentInstance;
  token :string

  paymentFailure() {
    console.log('Payment Failed');
  }

  paymentSuccess(res) {
    console.log('Payment complete', res);
    this.paymentInstance.close();
  }

  paymentInit(paymentInstance) {
    this.paymentFailure = paymentInstance;
    console.log('Payment about to begin', paymentInstance);
  }
}
```
then the issue is most probably from rave

**Comment by olajiredominic** [comment] 2019-10-28 20:41
Ohh alright thank you. Before i close this issue please your paymentInit method expects a parameter of paymentinstance but you seem not to be passing it when the method is called on both the component or directive. Do i pass an $event  ??

**Comment by ashinzekene** [comment] 2019-10-28 20:42
Yes please `(paymentInit)="paymentInit($event)"` sorry for that

**Comment by olajiredominic** [comment] 2019-10-28 20:42
Also what do you suggest i do if issue is from rave. could you help me test if you get the same issue. Although i didnt get similar when i used their test api.

**Comment by ashinzekene** [comment] 2019-10-28 20:44
Would be best if you create a [vanilla sandbox](https://codesandbox.io/s/vanilla) to try it out

**Closed as completed** 2019-10-28 20:50 UTC
